project:
  type: website
execute: 
  freeze: auto

website:
  title: "NAIL blogspace"
  site-url: https://nonlinearartificialintelligencelab.github.io
  description: "Rich content for NAIL"
  reader-mode: true
  sidebar: 
    search: true
  navbar:
    collapse: true
    right:
      - text: NCSU Home
        href: https://nail.sciences.ncsu.edu
      - about.qmd
      - icon: github
        href: https://github.com/NonlinearArtificialIntelligenceLab
        aria-label: GitHub
      - icon: rss
        href: index.xml
  open-graph: true
  search:
    location: navbar
    type: overlay
  page-footer:
    center: 
      - text: "© 2022 NAIL"
        href: https://nail.sciences.ncsu.edu

format:
  html:
    html-math-method: katex
    theme: theme.scss
    css: styles.css
    citations-hover: true
    footnotes-hover: true
    code-fold: true
    code-tools: true



